version: "3"

services:
  app:
    container_name: citybike-app
    restart: always
    stdin_open: true
    build: ./app
    image: hyeink/helsinkicitybike_app
    volumes:
      - ${WEBAPP_STORAGE_HOME}/app:/app
    ports:
      - "443:3000"
    links:
      - mongo
    networks:
      - backend
  mongo:
    container_name: citybike-mongo
    image: mongo
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    networks:
      - backend
      - services
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=bikeStations
    ports:
      - "27017:27017"
    command: mongod
  api:
    container_name: citybike-api
    build: ./api
    image: hyeink/helsinkicitybike_api
    env_file:
      - .env
    volumes:
      - ${WEBAPP_STORAGE_HOME}/api:/api
    environment:
      MONGO_DB_HOST: mongo
    networks:
      - backend
  services:
    container_name: citybike-services
    build: ./services
    image: hyeink/helsinkicitybike_services
    env_file:
      - .env
    volumes:
      - ${WEBAPP_STORAGE_HOME}/services:/services
    networks:
      - services
volumes:
  mongodata:
networks:
  backend:
  services: