version: "3"

services:
  app:
    container_name: citybike-app
    restart: always
    stdin_open: true
    build: ./app
    image: hyeink/helsinkicitybike_app
    volumes:
      - ${WEBAPP_STORAGE_HOME}/app/build:${PUBLIC_PATH}
    ports:
      - "8080:80"
    networks:
      - backend
      - helsinki-citybike
    env_file:
      - .env
    environment:
      API_URL: ${API_URL}
  mongo:
    container_name: citybike-mongo
    image: mongo
    volumes:
      - ${WEBAPP_STORAGE_HOME}/data:/data/db
    networks:
      - backend
      - services
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    command: mongod
  api:
    container_name: citybike-api
    build: ./api
    image: hyeink/helsinkicitybike_api
    volumes:
      - ${WEBAPP_STORAGE_HOME}/api:/api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      STATION_DB: ${STATION_DB}
      STATION_DB_USER: ${STATION_DB_USER}
      STATION_DB_PASSWORD: ${STATION_DB_PASSWORD}
      BIKE_TREND_DB: ${BIKE_TREND_DB}
      BIKE_TREND_USER: ${BIKE_TREND_USER}
      BIKE_TREND_PASSOWRD: ${BIKE_TREND_PASSOWRD}
    networks:
      - backend
      - helsinki-citybike
  services:
    container_name: citybike-services
    build: ./services
    image: hyeink/helsinkicitybike_services
    env_file:
      - .env
    environment:
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      BIKE_TREND_DB: ${BIKE_TREND_DB}
      BIKE_TREND_USER: ${BIKE_TREND_USER}
      BIKE_TREND_PASSOWRD: ${BIKE_TREND_PASSOWRD}
    volumes:
      - ${WEBAPP_STORAGE_HOME}/services:/services
    networks:
      - services
      - helsinki-citybike
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    environment:
      PUBLIC_PATH: ${PUBLIC_PATH}
    volumes:
      - ${WEBAPP_STORAGE_HOME}/app/build:${PUBLIC_PATH}
      - ${WEBAPP_STORAGE_HOME}/nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
      - "443:443"
    networks:
      - helsinki-citybike
networks:
  helsinki-citybike:
    driver: bridge
  backend:
  services: