version: "3"

services:
  app:
    container_name: citybike-app
    restart: always
    stdin_open: true
    build: ./app
    image: hyeink/helsinkicitybike_app
    volumes:
      - ${WEBAPP_STORAGE_HOME}/app/build:/var/www/public
    ports:
      - "8080:80"
    links:
      - mongo
    networks:
      - backend
      - helsinki-citybike
  mongo:
    container_name: citybike-mongo
    image: mongo
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    networks:
      - backend
      - services
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=bikeStations
    ports:
      - "27017:27017"
    command: mongod
  api:
    container_name: citybike-api
    build: ./api
    image: hyeink/helsinkicitybike_api
    env_file:
      - .env
    volumes:
      - ${WEBAPP_STORAGE_HOME}/api:/api
    ports:
      - "3000:3000"
    environment:
      MONGO_DB_HOST: mongo
    networks:
      - backend
      - helsinki-citybike
  services:
    container_name: citybike-services
    build: ./services
    image: hyeink/helsinkicitybike_services
    env_file:
      - .env
    volumes:
      - ${WEBAPP_STORAGE_HOME}/services:/services
    networks:
      - services
      - helsinki-citybike
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ${WEBAPP_STORAGE_HOME}/app/build:/var/www/public
      - ${WEBAPP_STORAGE_HOME}/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - helsinki-citybike
volumes:
  mongodata:
networks:
  helsinki-citybike:
    driver: bridge
  backend:
  services: