version: "3"

services:
  app:
    container_name: citybike-app
    restart: always
    stdin_open: true
    build: .
    ports:
      - "443:3000"
    links:
      - mongo
    networks:
      - backend
  mongo:
    container_name: citybike-mongo
    image: mongo
    env_file:
        - .env
    volumes:
      - data:/data/db
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=bikeStations
    command: mongod
  api:
    container_name: citybike-api
    build: ./api
    ports:
      - "8081:3000"
    volumes:
      - ./api:/api
    networks:
      - backend
volumes:
  data:
networks:
  backend: