version: "3"

services:
  app:
    container_name: citybike-app
    restart: always
    stdin_open: true
    build: ./app
    image: hyeink/helsinkicitybike_app
    volumes:
      - ./app/build:${PUBLIC_PATH}
    ports:
      - "8080:80"
    networks:
      - backend
      - helsinki-citybike
    env_file:
      - .env
  mongo:
    container_name: citybike-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
      - services
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    command: mongod
  api:
    container_name: citybike-api
    restart: on-failure
    build: ./api
    image: hyeink/helsinkicitybike_api
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - backend
      - helsinki-citybike
  services:
    container_name: citybike-services
    restart: on-failure
    build: ./services
    image: hyeink/helsinkicitybike_services
    env_file:
      - .env
    volumes:
      - ./services:/services
    networks:
      - services
      - helsinki-citybike
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - ./app/build:${PUBLIC_PATH}
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
      - "443:443"
    networks:
      - helsinki-citybike
networks:
  helsinki-citybike:
    driver: bridge
  backend:
  services: